### ISSUE TITLE
Install FreeBSD: Add geli encryption option during install

### ISSUE THREAD

**Issue by afhpayne** [helloSystem/Utilities#76] opened 2021-07-05 15:18 UTC
Geli encryption is available in the FreeBSD installer, can you pull that functionality into the helloSystem installer?

**Comment by probonopd** [comment] 2023-03-18 17:09
Closing as a duplicate of
* https://github.com/helloSystem/ISO/issues/15

**Closed** 2023-03-18 17:09 UTC
