### ISSUE TITLE
Ship a character map utility

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#142] opened 2022-12-13 14:13 UTC
We use special symbols when typing official documents, but the system is very troublesome without them.

![image](https://user-images.githubusercontent.com/44593430/207355395-8866a0a5-9a5d-4af6-8550-5c81410d9f29.png)

In CJK user

![image](https://user-images.githubusercontent.com/44593430/207356362-48ebe2b1-b48c-4d04-ad41-e1347dd68d59.png)

**Comment by louies0623** [comment] 2022-12-21 21:42
I'm guessing it's because there are a lot of languages ​​to deal with, so in C++ and not PY.
![py_vs_cpp](https://user-images.githubusercontent.com/44593430/209007430-3dcb592f-3ae4-4b35-85d7-78b56b7d7632.png)

**Comment by probonopd** [comment] 2023-01-02 18:41
Closing as a duplicate of https://github.com/helloSystem/ISO/issues/95.

**Closed by probonopd** 2023-01-02 18:41 UTC
