### ISSUE TITLE
Falkon - Icon of function button on multiple windows will not see

### ISSUE THREAD

**Issue by louies0623** [helloSystem/Utilities#74] opened 2021-07-01 19:34 UTC
After opening more than one window, the Icon of function button above will disappear.

**Comment by probonopd** [comment] 2021-07-05 23:17
Thanks for reporting @louies0623. Duplicate of https://github.com/helloSystem/QtPlugin/issues/8, hence closing here.
Do you have an idea on how to debug this?

**Closed by probonopd** 2021-07-05 23:17 UTC
